### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by jonsterling** [ekmett/lens-action#3]
Presently, the build fails (both on hackage and on my machine) with:

````
Could not find module `Control.Lens.Action.Type`
````

If I get some time today, I can try fixing it (unless there is already a fix queued up).

**Comment by jonsterling** [comment]
For what it's worth, when I clone this repository the build works (it's just the version that comes from hackage that doesn't). Maybe it has already been fixed and just needs to be uploaded?

**Comment by jonsterling** [comment]
OK, looks like this is just a dupe of #2, so I'll close this issue. It'd be very helpful if the fixed version could be uploaded to Hackage shortly; thanks! :)

**Comment by glguy** [comment]
This is similar to #2 but not same. Fix needed.
